### ISSUE TITLE
[Data 환경 구축하기] API_ API 받아오는 코드 수정 진행

### ISSUE THREAD

**Issue by hyeming-king** [KartTrack-lap/Kartrider-game-analysis#10]
Api 데이터 가져오는 코드를 수정하기!
코드 수정사항은 이슈 댓글로 달아주시고 슬랙이나 노션에도 작성해주세요 ☺️

**Comment by junetofeb** [comment]
# 221022 성과


### 1. 날짜 데이터 형식 변경
    - '%Y.%m.%d %H:%M:%S' → '%Y-%m-%d %H:%M:%S' 으로 수정 변경
- 기존의 날짜 데이터 형식은 카트라이더 api에서 호출 시 필요로 하는 날짜형이 아니어서, 자동으로 '현재'를 기준으로 데이터를 추출하였음
    - 해서 매번 다른 데이터가 추출되거나, 21년 데이터를 추출했는데 22년에 출시된 메이플스토리 맵이 포함되는 등의 trouble issues 발생
 

### 2. 최종 single, team DataFrame 컬럼 추가
- matchId에 따른 실제 게임 시작/종료 시간, 추출에 사용된 start / end time  추가
- 실제 게임 시작/종료 시간과 추출 기준 시간 비교하여 데이터 정합성 검증 위함


### 3. JSON metadata 기반 matchType명 추출하는 코드 추가
- 기존 unicode 기반 matchType을 쉽게 식별 가능하도록 함

### 4. offset 변수 [0, 200] 에서 try ~ except 구문 추가
 - 날짜 데이터 형식 변경 후, 제대로 된 데이터가 출력되며 해당 시간에 offset 200 이상 되지 않는 경우 len() 값이 모자라다는 오류 출력되었음
 - offset 200 이상 되지 않는 부분은 except로 처리해서 에러 발생하지 않도록 함

**Comment by hyeming-king** [comment]
## Test 데이터 뽑기
10/03 ~ 10/04일 진행
### match id 뽑는 것은 성공, 해당 id로 특정매치 상세 정보 조회 데이터 가져올 떄
(저의 경우!)
- 하루, 30분 단위 -> 실패 
- 하루, 1시간 단위 -> 실패
- **반나절(12시간) 1시간 단위 -> 성공**  => 10분 소요

### 이로 유추할 수 있는 결과
- 많은 양의 데이터를 호출한다면, 넥슨 서버에서 연결을 끊는 현상으로 예상함
<span style='color:#2D3748; background-color:##fff51;'>**-> 실패 오류 메세지를 확인시 타임에러, 커넥션 에러 발생으로 예측가능.**</span>

### 제안
- **하루 데이터를 조절해서 가져오기**
- 위의 방법과 추가로 매치 상세 데이터 조회에도 sleep을 걸어주는 방안을 추가로 진행해야 할 것 같음
 -> 코드 업데이트 예정!
- 현재 코드 추가하고 하루, 1시간 단위 테스트 중
```
# 매치 상세 정보 조회에서
# def get_playerdata(match_df):
    # api를 돌림
    for i in tqdm(range(0, len(match_df))):
        if i%50==0:
            time.sleep(5)
```

**Comment by hyeming-king** [comment]
sleep 함수 추가하니, 하루, 1시간 단위 테스트 성공하여 해당 부분 코드에 추가하였습니다!
```
if i%50==0:
            time.sleep(5)
```

**Comment by hyeming-king** [comment]
API 가져오는 코드 정상 작동 확인, 분석에 필요한 한달치 데이터 수집하였으므로 이슈 닫습니다.
