### ISSUE TITLE
[데이터 import] - MySQL 데이터 업로드

### ISSUE THREAD

**Issue by junetofeb** [KartTrack-lap/Kartrider-game-analysis#13]
# Python을 이용하여 MySQL에 데이터를 바로 업로드 하는 방법입니다
- MySQL에 반드시 SCEMA를 먼저 생성 후 시도해주세요!
- 생성한 SCEMA이름에 따라 변수 명을 수정해 주세요!

**Comment by hyeming-king** [comment]
해당 코드로 추후 작업할 수 있다 판단하여, 이슈 닫겠습니다!
