### ISSUE TITLE
[자료수집] 카트라이더 맵 관련조사, 업데이트 이벤트(카트, 맵, 아이템) 조사

### ISSUE THREAD

**Issue by hyeming-king** [KartTrack-lap/Kartrider-game-analysis#2]
### Map 관련

- [x] 맵 분류
- [ ] 레벨별 맵 가능
- [ ] 직선, 곡선, 회전 코스 개수

### 업데이트 관련

- [x] 업데이트 : 기간, 거시적인 업데이트 요소(대규모)
- [x] 업데이트 항목 : 카트, 밴드, 풍선, 이벤트, 맵추가(큰업데이트)
- [x] 업데이트 카트 정보

**Comment by hoinnovation** [comment]
# 2022.10.13의 성과
## Track 관련 
## 1. 진행한 것 
트랙 전체에 대해 파악 및 구글 스프레드시트로 저장
- (1) 메타데이터(22.10.13 11:00기준)의 트랙 개수 파악 : 스피드, 팀, 리그 등 (344개)
- (2) tmi에서 스피드 개인, 스피드 팀 트랙 데이터 크롤링(Listly이용) : 스피드 개인(325개), 스피드 팀(321개)
![image](https://user-images.githubusercontent.com/45919197/195524619-43012fba-509d-44eb-858f-63808b427d11.png)


## 2. 진행 할 것 
-  (1) 크롤링(트랙 길이, 진행 방향, 첫 등장일) 데이터와 연결 
-  (2) 트랙 이미지 라벨링 방안 고민
(곡선, 직선 라벨링)
- (3) 게임 진행하면서 파악할 것
    - 어떤 칼럼 추가할지 고민 (장애물 여부, 오르막길, 직선 등)
    - 모드(이지, 노멀, 하드 등) 설정 시 트랙 난이도 변경되는지 확인


## 업데이트 관련 
## 1. 진행한 것 
카트라이더 공식홈페이지에 있는 업데이트/패치중 카트와 트랙 파악 (22.08.18 ~ 22.10.13)
- (1) 트랙 
   - 신규 트랙 추가 : 2개 
   - 기존 트랙 개선 : 48회 (중복 트랙 포함)
- (2) 카트 : 66회
![image](https://user-images.githubusercontent.com/45919197/195534193-6b89c2c9-689d-4044-9bff-05bac018bef8.png)


## 2. 진행 할 것 
- (1) 카트 이벤트를 기준으로 진행할지 확인
   - 공식 홈페이지로 정리하기에는 이벤트가 너무 많다. 그리고 카트라이더는 이전에 나온 카트를 이벤트로 다시 제공하기 도 한다. 
   -  카트를 기준으로 진행한다면, 나무위키( ex. 2021년 출시 카트)에서 정보 정리
