### ISSUE TITLE
[Data 통계분석] 3일치 데이터 통계분석 테스트

### ISSUE THREAD

**Issue by goodkse7** [KartTrack-lap/Kartrider-game-analysis#21]
- [x] 회정 : year로 독립변수, month 로 독립변수 단순 회귀 돌려보기 + 추가로 다른 변수를 합치면서 (시간 위주로) 
- [x] 시은 : 트랙 9 등 일부 트랙 제외하고 회귀분석 진행해보기
- [ ] 효진 : 종속변수를 rank로 변환해서 ols 단순 회귀 해보기
- [x] 혜민 : 각 변수 경향성 확인하기 → 왜도, 첨도 값 구하고 → 경향 있으면 이슈에 공유 → 전부 다 진행하면 회귀분석 넣고 빼고 하면서 진행

**Comment by goodkse7** [comment]
# 트랙9 등 일부 트랙 제외하여 회귀 분석 진행

## <트랙9 제외한 데이터 회귀분석>

1. 평균 매치 타임을 독립변수로 뒀을 때, 로그 변환 한 것과 안한 것 모두 R제곱이 하락함
   * 로그 변환 안한 것 : 0.164 -> 0.137
   * 로그 변환 한 것 : 0.233 -> 0.202

아래는 모두 로그 변환하여 진행함

2. 평균 매치 타임 + 트랙길이 / 리타어율 모두 수정R제곱 상승, AIC BIC 하락. Pvalue<0.05
   * 로그 사용건수 <- 평균 매치 타임, 트랙길이 : 수정R제곱 0.270
   * 로그 사용건수 <- 평균 매치 타임, 리타이어율 : 수정R제곱 0.266
   * 로그 사용건수 <- 평균 매치 타임, 트랙길이, 리타이어율 : 수정R제곱 0.382
   특이한 건 리타이어율의 기울기가 양수.

3. 그 외 지표
   * 로그 사용건수 <- 로그 평균 매치 타임, 맵 난이도 : 0.197, P-value>0.05
   * 로그 사용건수 <- 로그 평균 매치 타임, 연도 : 0.198, P-value>0.05
   * 로그 사용건수 <- 연도 : 0.000, P-value>0.05
   * 로그 사용건수 <- 월 : 0.000, P-value>0.05
   * 로그 사용건수 <- 랩 : 0.022, P-value>0.05 (0.146)
   * 로그 사용건수 <- 트랙길이 : 0.037, P-value>0.05 (0.057)

## <트랙9 + 사막 버려진 오아시스, 노르테유 허공의 갈림길 제외한 데이터 회귀분석>

> 매치당 평균 플레이어수를 봤을 때 트랙9과 비슷한 성격을 가지고 있다고 생각한 두 트랙을 추가로 제외하여 분석 시도

결과적으로 트랙9만 제거한 데이터에 비해 모든 모델에서 R제곱이 하락함

**Comment by goodkse7** [comment]
# 기존 데이터 추가 회귀 분석
## <year과 month를 독립변수로 한 단순 회귀 분석>
-> 연, 월을 각각 따로 회귀분석을 했을 때 로그변환 한 것과 안한 것 모두 유의미한 결과가 나오지 않음.
1. 로그변환 X
    * 사용건수 <- 연 : R제곱 0.009
    * 사용건수 <- 월 : R제곱 0.05
2. 로그변환 O
    * 사용건수 <- 연 : R제곱 0.000
    * 사용건수 <- 월 : R제곱 0.000

## <추가 회귀분석>
트랙9을 제외한 데이터에서 분석 결과가 좋았던 모델을 원본 데이터에도 적용해 봄.
-> 로그변환을 하지 않은 모델에서는 유의미한 결과를 얻지 못함

1. 로그변환 X
    * 사용건수 <- 평균 매치타임 + 트랙길이 : 0.166 AIC 1355 BIC 1363 P-value 0.599
    * 사용건수 <- 평균 매치타임 + 리타이어율 : 0.164 AIC 1356 BIC 1364 P-value 0.907
2. 로그변환 O
    * 사용건수 <- 평균 매치타임 : 0.233 AIC 324.4 BIC 329.6
    * 사용건수 <- 평균 매치타임 + 트랙길이 : 0.291 AIC 317.4 BIC 325.2
    * 사용건수 <- 평균 매치타임 + 리타이어율 : 0.295 AIC 316.9 BIC 324.7
    * 사용건수 <- 평균 매치타임 + 리타이어율 + 트랙길이 : 0.415 AIC 302.2 BIC 312.6

결과적으로 트랙9만 제거한 데이터에 비해 모든 모델에서 R제곱이 하락함

**Comment by hyeming-king** [comment]
### Year 에 관련한 EDA

**상위 트랙, 하위 트랙에 포함되는 트랙 제작 연도 횟수**
<img width="517" alt="image" src="https://user-images.githubusercontent.com/84497369/198171771-4d133c6f-9ac0-4cd8-ada5-7bbef402f26c.png">


<img width="561" alt="image" src="https://user-images.githubusercontent.com/84497369/198188800-84109d52-c6ca-43c2-b1b0-a93e05c9ac38.png">

- **균등분포 형태가 아니므로 연도에 트랙이 영향을 것은 아니라고 할 수는 없지만 옛날에 나온 맵이 인기있다? 최근의 맵이 인기 없다? 고 말하기는 힘들어보임**
- 상위 트랙을 보면, 2004, 2011 옛날 트랙이 많이 있지만, 2021년, 2022년 등 최신 년도의 트랙도 상위에 랭크된 것을 볼 수 있음
- 하위 트랙도 마찬가지로 2007년 등 옛날 연도의 트랙도 많이 포함된 것 + 최신 트랙 2022년.


----
-> 넥슨에서 연도별로 제작된 트랙의 개수 차이가 클 수도 있음 따라서 하위에도 상위에도 옛날 많이 들어갈 수도 있음.
    ex) 2004년 맵 50개 제작, 2022 년 맵 3개 제작
-> 전체 기간을 한달 데이터, 상위 하위를 다시 나누어 살펴본다면, 다시 한번 진행해보면 결과 달라질 수도 있음!
