### ISSUE TITLE
[Data 전처리] crawl-data-with-theme + api_Kpi 데이터 조인

### ISSUE THREAD

**Issue by hoinnovation** [KartTrack-lap/Kartrider-game-analysis#30]
#  Issue : [Data 전처리]

# Description
재 merge한 crawl-data-with-theme와 API기반 KPI 데이터를 조인합니다.
merged된 API_KPI데이터를 바탕으로 상위/하위 트랙을 추출합니다.

# To-do
API 기반 KPI 데이터를 기준으로 재 merge한 crawl-data-with-theme를 붙여, KPI의 name(track_name) 기준 데이터가 남도록 합니다.

# ETC
#31 API_KPI 데이터 기반 **상위/하위 트랙 데이터**에서 결측치 채우기 후속 작업이 필요합니다.

**Comment by junetofeb** [comment]
# To-do : KPI데이터에 크롤링 데이터 붙이기

# Completed
KPI의 name을 기준으로 API_KPI와 crawling 데이터를 머지하여 KPI 데이터에 크롤링 데이터를 붙였습니다.
b7508da

# To-do
- [x] 후속 작업으로 KPI 데이터의 결측치 채우기 작업이 필요합니다. (#31) @junetofeb 

해당 이슈 해결 완료하여 이슈 Close 합니다!
