### ISSUE TITLE
[Data 전처리] crawl-data-with-theme + api_Kpi 결측치 채우기

### ISSUE THREAD

**Issue by hoinnovation** [KartTrack-lap/Kartrider-game-analysis#31]
#  Issue : [Data 전처리]

# Description
#30 에서 확인한 API_KPI 데이터 기반 상위/하위 트랙의 결측치를 수기로 채워넣습니다.
해당 결측치는 Crawling 단계에서 크롤링이 불가능하였던 데이터로 수기작업이 불가피합니다!

# To-do
카트라이더 공식 문서 기준 결측치를 수가로 채워넣었습니다!

# ETC
이 작업을 끝으로  API_KPI 데이터 기반 상위/하위 트랙 데이터가 완성됩니다👏👏

**Comment by junetofeb** [comment]
# To-do : 상위/하위 트랙 결측치 수기 입력

# Completed
상위/하위 데이터 결측치 채워넣는 작업이 모두 완료되었습니다.
47877ba, 35a0028

모든 문제 해결 완료되어 해당 이슈 닫습니다! 🥳👏
